<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="CloudinaryDotNet" Version="1.29.0" />
		<PackageReference Include="Google.Apis.Auth" Version="1.74.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.8" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="8.0.8" />
		<PackageReference Include="MySql.EntityFrameworkCore" Version="8.0.8" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.2" />
		<PackageReference Include="QRCoder" Version="1.8.0" />
		<PackageReference Include="QuestPDF" Version="2026.6.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EcomPlatform.Application\EcomPlatform.Application.csproj" />
		<ProjectReference Include="..\EcomPlatform.Core\EcomPlatform.Core.csproj" />
		<ProjectReference Include="..\EcomPlatform.Shared\EcomPlatform.Shared.csproj" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.1.0" />
	</ItemGroup>

</Project>